tasks:
  - name: update npm
    init: npm update -g npm

  - name: install snyk
    init: npm install snyk
    
  - name: install-pretty-cat
    init: sudo apt install -y bat
    
  - name: aws-cli
    env: 
      AWS_CLI_AUTO_PROMPT: on-partial
    init: |
      cd /workspace
      curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      unzip "awscliv2.zip"
      sudo ./aws/install
      cd $THEIA_WORKSPACE_ROOT

vscode:
  extensions:
    - 42Crunch.vscode-openapi
